name: "Cloud Native Foundation Test Suite"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch: [amd64, arm, arm64]
        os: [ubuntu-latest]
        
    name: "cnf-testsuite"
    runs-on: ${{ matrix.os }}
    steps:

      - name: "Create Cluster with 1 master, 2 workers"
        uses: AbsaOSS/k3d-action@v2
        with:
          cluster-name: "test-cluster-1"
          args: --agents 2
          
      - name: Test on k3s
        run: |
          echo "KUBECONFIG=~/.kube/config" >> GITHUB_ENV
          kubectl version
          kubectl get nodes
          kubectl get pods -A
          sleep 20
          kubectl get nodes
          kubectl get pods -A
    
      - name: "run actions/checkout@v3"
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: false
          
      - name: "Install the latest test suite binary"
        run: |
          ./curl_install.sh
          echo "$HOME/.cnf-testsuite" >> $GITHUB_PATH

      - name: "Prepare the cnf-testsuite"
        run: cnf-testsuite setup

      - name: "Initialize the test suite for using the CNF"
        run: cnf-testsuite cnf_setup cnf-config=./example-cnfs/coredns/cnf-testsuite.yml

      - name: "Run all of application/workload tests"
        run: |
          KUBECONFIG=~/.kube/config
          cnf-testsuite workload

